### ISSUE TITLE
Contract deployment on testnet

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#194]
- [x] #617
- [x]  Run the deployment script
- [x] #839
- [x] Run the smoke tests (defined in #839)
- [x]  Publish the address of deployed contract somewhere (website?)
- [x] Commit the deployment information (json file) contracts/deployments/goerli into the CAPE repository
-  [x] Key generation
    -  [x] Use AZTEC public parameters
    -  [x] Plonk verifying keys
- [x] Define (duplication of #210)
  -  Set height of the merkle tree
  - Set number of roots: 1000 since #513 
- [x] #604
  + If we use ropsten, a repo to setup a miner and mine is at https://github.com/SpectrumXYZ/ethminer-ropsten
 - [x] CAP native token faucet @alxiong 
   - [x] update the public address of the faucet wallet in our deployment script (since we change our mnemonic) #616 
   - [x] #763 
- [x] #834
