### ISSUE TITLE
[Meta] Gas optimizations

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#22]
https://gitlab.com/translucence/cap-on-ethereum/cape/-/issues/74

**Comment by alxiong** [comment]
reading this [OZ forum discussion](https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966/6), there seems to be some low hanging fruit to save some gas,

- [ ] [custom error ](https://blog.soliditylang.org/2021/04/21/custom-errors/) for lower deploy time and runtime cost
- [ ] [caching the length in loops](https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966/6#caching-the-length-in-for-loops-2)
- [ ] use `calldata` instead of `memory` for readonly function parameters
- [ ] some state variables set to `immutable`
- [ ] [unchecked loop postcondition](https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966/6#the-increment-in-for-loop-postcondition-can-be-made-unchecked-6)
- [ ] use left/right shift when possible in place of div or mul

**Comment by alxiong** [comment]
Another repo of gas saving tricks: https://github.com/kadenzipfel/gas-optimizations
