### ISSUE TITLE
Roadmap: Plonk verifier

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#3]
### TurboPlonk Verifier

- [x] #70 
- [x] struct definition: Proofs, VerifyingKey #117, #151
  - (among which fields like OpenKey and k_coset_repr can be shared across different vk) 
  - deseralizing proof into group and field elements
- [x] Point & Field validity check #40, #64
- [x] FS transcript 
  - [x] basic append and get challenges API
  - [x] higher level append vk, evals API #171 
- [x] #181
- [x] Algebraic operations
  - [x] field inversion (for division) 
  - [x] pairing #59
  - [x] #175
  - [x] #174 
  - [x] #173 
- [x] #9  
- [x] #45 
- [x] #10 (single proof is just a special case) 

### Transaction Validity Verifier

- [x] Transaction validity proof verification
  - [x] #346 
  - [x] #368 
  - [x] #367
  - [x] #385
## References:

- Aztec's Plonk [verifier](https://github.com/AztecProtocol/aztec-2-bug-bounty/blob/master/contracts/verifier/TurboVerifier.sol)
- Old [gitlab issue](https://gitlab.com/translucence/cap-on-ethereum/cape/-/issues/20)
