### ISSUE TITLE
Deliverable 1 (CAPE contract) checklist tickets 

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#522]
- [x] #575
- [x]  Link of repository into our company website @clu8 
- [x] #558
- [x]  All tests pass
- [x] #576
- [x]  README has instructions on how to set up development environment
    - [x]  CAPE repository
    - [x]  Jellyfish repository
- [x]  README has instructions on how to run tests
    - [x]  CAPE repository
    - [x]  Jellyfish repository
- [x] #559
- [x] #560
- [x] #577
    - [x]  CAPE repository
- [x]  ~~There is at least one test for every in-scope user story~~
- [x]  ~~A non-expert has succeeded at every in-scope user story without excessive expert help~~
- [x] #578
- [x] #561
- [x] #562
- [x] #579
- [x] #563
- [x]  ~~Simple instructions are prominently featured for the most important user stories~~
- [x]  ~~Calls to sleep, unwrap, exit, panic and other functions that can mask fragile behavior have been reviewed~~
- [x]  ~~The repo has code coverage analysis~~
- [x]  ~~Code coverage has been reviewed~~
- [x] #605
- [x]  ~~Github issue template~~
- [x]  ~~Github PR template~~
- [x]  ~~Contributing guideline (often [CONTRIBUTING.md](http://contributing.md/))~~
- [x]  ~~Code of conduct~~
- [x]  ~~Contributor License Agreement (CLA)~~
- [x]  ~~All services have status checks that are being monitored~~
- [x]  ~~Alerts are configured so the right people will be alerted, but only when really necessary.~~
- [x]  ~~We can inspect what exact version (git revision) of each service is running (for example by calling an endpoint).~~
