### ISSUE TITLE
No TODO comments, but Git Hub issues are fine

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#562]
Only CAPE repository.

Check the following directories
- [ ] contracts
  - [ ] #585
    - [ ] contracts/contracts/libaries/BN254.sol
    - [ ] contracts/contracts/verifier
    - [ ] contracts/rust/plonk_verifier/mod.rs
- [ ] eqs
- [ ] relayer
- [ ] wallet
- [ ] nix,bin, main directory
