### ISSUE TITLE
Health check endpoints for services

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#708]
All APIs (for the demo: relayer, EQS, address book) should have a health check endpoint that responds with HTTP 200 if the service is okay.

- The simplest version can simply return 200 so that anything monitoring the service can tell it is running. If it's not running we would then spin up another instance.
- If desirable the services can do more extensive checks (for example check if their storage is working). We can consider this out of scope for the demo.

@Ancient123 do you have a preference for 
- HTTP status code and payload to return if service is **healthy**? `200, {"status": "available"}` ?
- HTTP status code and payload to return if service is **unhealthy** `503, {"status": "unavailable"}` ?
- Endoint? `/healthcheck` ?

### TODO
- [ ] Health check endpoint for relayer
- [ ] Health check endpoint for EQS
- [ ] Health check endpoint for address book
- [ ] Health check endpoint for faucet service

**Comment by nyospe** [comment]
This looks like something that could be included in the `net` repo and just added by each service.

**Comment by pictographer** [comment]
Manually checked for Address Book, EQS, relayer, faucet, and wallet web_server.
