### ISSUE TITLE
Deliverable 2 (CAPE Demo) checklist 

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#776]
- [x]  No dependencies on internal repositories
- [x]  All tests pass
- [x]  Check all README.md are up to date
- [x]  README has instructions on how to set up development environment
  - [x] EQS
  - [x] Relayer
  - [x] Wallet
  - [x] Address book
- [x]  README has instructions on how to run tests
- [x]  Instructions for obtaining help are included in all reasonable starting points, e.g. all the README.md files
- [x]  All repos have appropriate license
- [x]  [Check automatically that all files have the appropriate license](https://github.com/EspressoSystems/cape/issues/778)
- [x] #786
- [x] #920
- [x] #916
- [x] #918
   - [x] Wallet
- [x] #913
- [x]  ~~Github issue template~~
- [x]  ~~Github PR template~~
- [x]  ~~Contributing guideline (often CONTRIBUTING.md)~~
- [x]  ~~Code of conduct~~
- [x]  ~~Contributor License Agreement (CLA)~~
- [x]  [All services have status checks that are being monitored](https://github.com/EspressoSystems/cape/issues/708)
- [x] #915
- [x] CAPE contract is deployed and its address is available on the website

**Comment by philippecamacho** [comment]
Remove test coverage items on the list based on https://espresso.zulipchat.com/#narrow/stream/311688-CAPE/topic/Does.20it.20make.20sense.20to.20have.20test.20coverage.20for.20CAPE.3F/near/276932550
